name: $(Build.BuildId).$(Year:yy)$(DayOfYear)

trigger:
  - master

resources:
  repositories:
  - repository: templates
    type: git
    name: Audacia/Audacia.Build.Templates

stages:

- stage: Build
  displayName: Build
  jobs:

  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.ExceptionHandling
      projects: Audacia.ExceptionHandling/Audacia.ExceptionHandling.csproj

  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.ExceptionHandling.Annotations
      projects: Audacia.ExceptionHandling.Annotations/Audacia.ExceptionHandling.Annotations.csproj

  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.ExceptionHandling.AspNetCore
      projects: Audacia.ExceptionHandling.AspNetCore/Audacia.ExceptionHandling.AspNetCore.csproj

  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.ExceptionHandling.EntityFrameworkCore
      projects: Audacia.ExceptionHandling.EntityFrameworkCore/Audacia.ExceptionHandling.EntityFrameworkCore.csproj

  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.ExceptionHandling.FluentValidation
      projects: Audacia.ExceptionHandling.FluentValidation/Audacia.ExceptionHandling.FluentValidation.csproj

- stage: Release
  displayName: Release
  jobs:
  - template: jobs/release/netcore/public-package.yaml@templates